	</div>
	<footer>
		<span>
			<h1>The Monument</h1>
			<a class="button" href="#top">(back to top)</a>
		</span>
		<em>High Point Regional High School is a public high school located in rural Sussex County, NJ, where approximately 1200 students attend from 5 municipalities. <i>The Monument</i> is the official student paper and aims to encompass diversity, broaden our scope of influence and present our coverage with depth and style.</em>
		<!--<section id="browser">
			<h2>Browse All Articles by Section</h2>
			<ul id="categories">
				<?php
				//$cat = get_the_category();
				//$cat_current = $cat[0]->cat_ID;
				//wp_list_categories('orderby=ID&title_li=&depth=1&hide_empty=0&exclude=1&current_category='.$cat_current); ?>
			</ul>
			<ul id="articles">
				<li class="current">
					<h3>Article Title</h3>
					<small>by <em>Author</em> on Nov 27, 2010</small>
				</li>
				<li>
					<h3>Article Title</h3>
					<small>by <em>Author</em> on Nov 27, 2010</small>
				</li>
				<li>
					<h3>Article Title</h3>
					<small>by <em>Author</em> on Nov 27, 2010</small>
				</li>
			</ul>
			<div>
				<?php
				//	$dir = bloginfo('stylesheet_directory');
				//	include($dir.'browser.php');
				//	getArticle(6);
				?>
			</div>
		</section>-->
		<p>All content on this website is generated by the students of <a href="http://hpregional.org">High Point Regional High School</a>, except as noted. Web design by <a href="http://theopak.com">Theo Pak</a>.</p>
	</footer>

	<script type="text/javascript" src="http://w.sharethis.com/button/buttons.js"></script>



	<!-- JavaScript at the bottom for fast page loading -->

	<!-- Grab Google CDN's jQuery, with a protocol relative URL; fall back to local if offline -->
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.js"></script>
	<script>window.jQuery || document.write('<script src="js/libs/jquery-1.6.2.min.js"><\/script>')</script>

	<!-- scripts concatenated and minified via ant build script-->
	<script defer src="js/plugins.js"></script>
	<script defer src="js/script.js"></script>
	<!-- end scripts-->

	<script src="http://use.typekit.com/qqt1yab.js"></script>
	<script>
		//enable Typekit
		try{Typekit.load();}catch(e){}
		
		//Google Analytics (asynchronous)
		var _gaq=[["_setAccount","UA-22233583-1"],["_trackPageview"]];
		(function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];g.async=1;
		g.src=("https:"==location.protocol?"//ssl":"//www")+".google-analytics.com/ga.js";
		s.parentNode.insertBefore(g,s)}(document,"script"));
	</script>

	<!-- Prompt IE 6 users to install Chrome Frame. Remove this if you want to support IE 6.
		chromium.org/developers/how-tos/chrome-frame-getting-started -->
	<!--[if lt IE 7 ]>
		<script src="//ajax.googleapis.com/ajax/libs/chrome-frame/1.0.3/CFInstall.min.js"></script>
		<script>window.attachEvent('onload',function(){CFInstall.check({mode:'overlay'})})</script>
	<![endif]-->

	<?php wp_footer(); ?>

</body>
</html>